version: '3.8'
services:
  db:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5437:5432
    volumes: 
      - hub_orgs_db:/var/lib/postgresql/data
  redpanda:
    # NOTE: Use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --set redpanda.empty_seed_starts_cluster=false
    - --set redpanda.auto_create_topics_enabled=true
    - --seeds "redpanda-1:33145"
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --pandaproxy-addr
    - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
    - --advertise-pandaproxy-addr
    - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    - --advertise-rpc-addr redpanda-1:33145
    ports:
    - 8081:8081
    - 8082:8082
    - 9092:9092
    - 28082:28082
    - 29092:29092


  # ory hydra
  hydra:
    image: oryd/hydra:v2.0.3
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    env_file:
      - .env    
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./hydra.yml
        target: /etc/config/hydra/hydra.yml
    environment:
      - DSN=postgres://holaplex:holaplex@postgresd:5432/hydra?sslmode=disable&max_conns=100&max_idle_conns=100
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - hydra
  hydra-migrate:
    image: oryd/hydra:v2.0.3
    environment:
      - DSN=postgres://holaplex:holaplex@postgresd:5432/hydra?sslmode=disable&max_conns=100&max_idle_conns=100
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    env_file:
      - .env 
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./hydra.yml
        target: /etc/config/hydra/hydra.yml
    restart: on-failure
    networks:
      - hydra
  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v2.0.3
    ports:
      - "3010:3000"
    restart: unless-stopped
  postgresd:
    image: postgres:15.1
    ports:
      - "5132:5432"
    environment:
      - POSTGRES_USER=holaplex
      - POSTGRES_PASSWORD=holaplex
      - POSTGRES_DB=hydra
    networks:
      - hydra

  #SVIX
  backend:
    image: svix/svix-server
    environment:
      WAIT_FOR: "true"  # We want to wait for the default services
      SVIX_REDIS_DSN: "redis://redis:6379"
      # SVIX_DB_DSN: "postgresql://holaplex:holaplex@pgbouncer/svix"
      DATABASE_URL: "postgresql://holaplex:holaplex@svix-postgres:5432/svix?max_conns=500&max_idle_conns=100"
      SVIX_JWT_SECRET: ${SVIX_JWT_SECRET}
    ports:
      - "8071:8071"
    depends_on:
    - svix-postgres
    - redis
    networks:
      - svix

  svix-postgres:
    image: postgres:13.4
    ports:
      - "5232:5432"
    volumes:
      - "svix-postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_USER: holaplex
      POSTGRES_DB: svix
      POSTGRES_PASSWORD: holaplex
    networks:
      - svix
  redis:
    image: "redis:7.0.8-alpine"
    # Enable persistence
    command: "--save 60 500 --appendonly yes --appendfsync everysec"
    volumes:
      - "svix-redis-data:/data"  
    networks:
      - svix
networks:
  svix:
  hydra:
volumes:
  hub_orgs_db:
    driver: local
  hydra-sqlite:
  svix-postgres-data:
  svix-redis-data: