//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use async_graphql::{dataloader::DataLoader, *};
use sea_orm::entity::prelude::*;

use super::{organizations::Model as Organization, projects::Model as Project};
use crate::dataloaders::{project::CredentialId, OrganizationLoader, ProjectLoader};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject)]
#[sea_orm(table_name = "credentials")]
#[graphql(concrete(name = "Credential", params()))]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub client_id: String,
    pub organization_id: Uuid,
    pub name: String,
    pub created_at: DateTime,
    pub created_by: Uuid,
}

#[ComplexObject]
impl Model {
    async fn organization(&self, ctx: &Context<'_>) -> Result<Option<Organization>> {
        let loader = ctx.data::<DataLoader<OrganizationLoader>>()?;
        loader.load_one(self.organization_id).await
    }

    async fn projects(&self, ctx: &Context<'_>) -> Result<Option<Vec<Project>>> {
        let loader = ctx.data::<DataLoader<ProjectLoader>>()?;
        loader.load_one(CredentialId(self.id)).await
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
