//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use async_graphql::*;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::{members, organizations, sea_orm_active_enums::InviteStatus};
use crate::AppContext;

/// An invitation sent to join a Holaplex organization.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject, Serialize, Deserialize)]
#[sea_orm(table_name = "invites")]
#[graphql(complex, concrete(name = "Invite", params()))]
pub struct Model {
    /// The ID of the invitation.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// The email address of the user being invited to become a member of the organization.
    pub email: String,
    /// The status of the invitation.
    pub status: InviteStatus,
    /// The ID of the organization to which the invitation belongs.
    pub organization_id: Uuid,
    /// The ID of the user who created the invitation.
    pub created_by: Uuid,
    /// The datetime, in UTC, when the invitation to join the organization was created.
    pub created_at: DateTimeWithTimeZone,
    /// The datetime, in UTC, when the invitation status was updated.
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[ComplexObject]
impl Model {
    /// The member record that is generated after the invitation to join the organization is accepted. When the user has not accepted the invitation, this field returns `null`.
    async fn member(&self, ctx: &Context<'_>) -> Result<Option<members::Member>> {
        let AppContext {
            invite_member_loader,
            ..
        } = ctx.data::<AppContext>()?;

        invite_member_loader.load_one(self.id).await
    }

    /// The organization to which the invitation to join belongs.
    async fn organization(&self, ctx: &Context<'_>) -> Result<Option<organizations::Organization>> {
        let AppContext {
            organization_loader,
            ..
        } = ctx.data::<AppContext>()?;

        organization_loader.load_one(self.organization_id).await
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
