//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use async_graphql::*;
use sea_orm::entity::prelude::*;

use super::organizations::Model as Organization;
use crate::AppContext;

#[derive(Clone, Copy, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "members")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub organization_id: Uuid,
    pub created_at: DateTime,
    #[sea_orm(nullable)]
    pub revoked_at: Option<DateTime>,
}

#[derive(Clone, Copy, SimpleObject, Debug)]
#[graphql(complex)]
pub struct Member {
    pub id: Uuid,
    pub user_id: Uuid,
    pub organization_id: Uuid,
    pub created_at: DateTime,
    pub revoked_at: Option<DateTime>,
}

#[ComplexObject]
impl Member {
    async fn organization(&self, ctx: &Context<'_>) -> Result<Option<Organization>> {
        let AppContext {
            organization_loader,
            ..
        } = ctx.data::<AppContext>()?;

        organization_loader.load_one(self.organization_id).await
    }
}

impl From<Model> for Member {
    fn from(
        Model {
            id,
            user_id,
            organization_id,
            created_at,
            revoked_at,
        }: Model,
    ) -> Self {
        Self {
            id,
            user_id,
            organization_id,
            created_at,
            revoked_at,
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
