//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5
#![allow(clippy::all)]
use async_graphql::{dataloader::DataLoader, *};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::{members, owners};
use crate::dataloaders::{MembersLoader, OwnerLoader};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "organizations")]
#[graphql(complex, concrete(name = "Organization", params()))]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Uuid")]
    pub id: uuid::Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub created_at: DateTime,
    #[sea_orm(nullable)]
    pub deactivated_at: Option<DateTime>,
}

#[ComplexObject]
impl Model {
    async fn members(&self, ctx: &Context<'_>) -> Result<Option<Vec<members::Model>>> {
        let loader = ctx.data::<DataLoader<MembersLoader>>()?;
        loader.load_one(self.id).await
    }

    async fn owner(&self, ctx: &Context<'_>) -> Result<Option<owners::Model>> {
        let loader = ctx.data::<DataLoader<OwnerLoader>>()?;
        loader.load_one(self.id).await
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::members::Entity")]
    Members,
    #[sea_orm(has_one = "super::owners::Entity")]
    Owners,
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub fn find_by_id(id: Uuid) -> Select<Self> {
        Self::find().filter(Column::Id.eq(id))
    }

    pub fn find_by_name(name: &str) -> Select<Self> {
        Self::find().filter(Column::Name.eq(name))
    }
}
