//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5
#![allow(clippy::all)]
use async_graphql::*;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::{credentials, members, owners};
use crate::{dataloaders::credential::OrganizationId, AppContext};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "organizations")]
#[graphql(complex, concrete(name = "Organization", params()))]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Uuid")]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub created_at: DateTime,
    pub deactivated_at: Option<DateTime>,
    pub svix_app_id: String,
}

#[ComplexObject]
impl Model {
    async fn members(&self, ctx: &Context<'_>) -> Result<Option<Vec<members::Member>>> {
        let AppContext { members_loader, .. } = ctx.data::<AppContext>()?;
        members_loader.load_one(self.id).await
    }

    async fn owner(&self, ctx: &Context<'_>) -> Result<Option<owners::Owner>> {
        let AppContext { owner_loader, .. } = ctx.data::<AppContext>()?;
        owner_loader.load_one(self.id).await
    }

    async fn credentials(&self, ctx: &Context<'_>) -> Result<Option<Vec<credentials::Model>>> {
        let AppContext {
            credential_loader, ..
        } = ctx.data::<AppContext>()?;
        credential_loader.load_one(OrganizationId(self.id)).await
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::members::Entity")]
    Members,
    #[sea_orm(has_one = "super::owners::Entity")]
    Owners,
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub fn find_by_id(id: Uuid) -> Select<Self> {
        Self::find().filter(Column::Id.eq(id))
    }

    pub fn find_by_name(name: &str) -> Select<Self> {
        Self::find().filter(Column::Name.eq(name))
    }
}
