//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use poem_openapi::Object;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, Copy, PartialEq, DeriveEntityModel, Eq, Object)]
#[sea_orm(table_name = "owners")]
#[oai(rename = "Owner", read_only_all)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub organization_id: Uuid,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub fn find_by_user(id: Uuid) -> Select<Self> {
        Self::find().filter(Column::UserId.eq(id))
    }
}
