//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use poem_openapi::Object;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Object)]
#[sea_orm(table_name = "projects")]
#[oai(rename = "Project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[oai(read_only)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub organization_id: Uuid,
    #[oai(read_only)]
    pub created_at: DateTime,
    #[sea_orm(nullable)]
    #[oai(read_only)]
    pub deactivated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizations,
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub fn find_by_id(id: Uuid) -> Select<Self> {
        Self::find().filter(Column::Id.eq(id))
    }
}
