//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use poem_openapi::Enum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Copy,
    Serialize,
    Deserialize,
    Default,
    Enum,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "invitie_status")]
pub enum InviteStatus {
    #[sea_orm(string_value = "accepted")]
    Accepted,
    #[sea_orm(string_value = "revoked")]
    Revoked,
    #[sea_orm(string_value = "sent")]
    #[default]
    Sent,
}
