[package]
name = "graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
actix-web = "4.2.1"
async-graphql-actix-web = "5.0.3"
dotenv = "0.15.0"
hub-core = { path = "../core" }