name: Cargo test
on: [push, pull_request]

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1

        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_PORT: 5432
          POSTGRES_DB: ci

        ports:
          - 5432:5432

    steps:
        - uses: actions/checkout@v3
        - uses: actions-rs/toolchain@v1
          with:
              toolchain: nightly
              override: true
              components: cargo, rustc

        - uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'rust-toolchain.toml') }}
        
        - name: cargo test
          uses: actions-rs/cargo@v1
          env:
            DATABASE_URL: postgres://ci:ci@127.0.0.1:5432/ci
          with:
            command: test